### ISSUE TITLE
Incompatibility with FirstPersonModel

### ISSUE THREAD

**Issue by ColdIce1605** [exaskye/Ears#10]
It doesn't seem like this mod handles transparency. Case in point this [no worky worky](https://ibb.co/ynprbqD)

**Comment by ColdIce1605** [comment]
I have no idea why the black stuff is happening but here's the skin.
https://ibb.co/HdkQxYD

**Comment by Suzriel** [comment]
Transparency works fine for me.

**Comment by ColdIce1605** [comment]
hmm transparency is always a issue with me and I have no idea can you try out my skin to see if its the skin
@Voidliest

**Comment by Suzriel** [comment]
My guess then is you saved as an image format that isn't **.PNG**. That is the only format that is supported I'm pretty sure.

**Comment by ColdIce1605** [comment]
nope its png

**Comment by ColdIce1605** [comment]
2020_11_12_arctic-fox-v3_wo_clothes_ears_comp.png

**Comment by ColdIce1605** [comment]
plus when you save as it saves it as a png

**Comment by Suzriel** [comment]
Okay. Well then it's either a bug or when you saved it some errors occurred (as in launcher or software).

**Comment by ColdIce1605** [comment]
@unascribed any thought I used gimp

**Comment by exaskye** [comment]
Another mod is conflicting with Ears' patches to the skin loader that prevent vanilla from overzealously forcing opacity on the skin. (See the wiki for more info)

Please send your client log.

**Comment by ColdIce1605** [comment]
Well my first thought was first person model. But I got to check

**Comment by ColdIce1605** [comment]
@unascribed its FirstPersionModel
and heres the log
https://pastebin.com/3BxuiTgT
