### ISSUE TITLE
[Suggestion] Option to disable overlay layers

### ISSUE THREAD

**Issue by AntyMew** [exaskye/Ears#102]
Currently, making a skin look right both with and without the mod requires duplicating body parts. This looks bizarre with some body parts, especially the ears, tail, and wings. They usually end up on the overlay layers on vanilla skins anyways, so why not let them be disabled for the best of both worlds?

**Comment by Cynosphere** [comment]
There is a currently undocumented and inaccessible through the manipulator feature for removing sections of the skin for this exact purpose.

**Comment by AntyMew** [comment]
Really? I'm having trouble finding it in the source code, pray tell where I can find it?

**Comment by Infinidoge** [comment]
I believe it is here:
https://github.com/unascribed/Ears/blob/334d84452a1f3cc2dadbe62ce0879c8a685bcb90/common/src/main/java/com/unascribed/ears/common/EarsCommon.java#L108-L136

I personally have no idea how to enable the regions manually, but Una would know.
