### ISSUE TITLE
Incompatible with ModLoaderNFC

### ISSUE THREAD

**Issue by vskoldr21** [exaskye/Ears#105]
Summary
------------------------------
Installing Ears and ModloaderNFC in the same Minecraft instance causes a crash to desktop
[Error Log](https://gist.github.com/LumiEvi/cf0e3ee1c1229d2145582abece2b19a9)
[NFC Issue](https://github.com/New-Frontier-Craft/New-Frontier-Craft/issues/93)

Steps to Reproduce
------------------------------
1. Install New Frontier Craft v3.4.2. (MultiMC or Prism Launcher recommended for these steps, [Installation Instructions](https://newfrontiercraft.net/thread/116/install-new-frontier-craft))

2. Download [Ears](https://github.com/unascribed/Ears/releases/download/v1.4.5/ears-nfc-1.4.5.jar)

3. Move `ears-nfc-1.4.5.jar` to .minecraft folder of NFC Instance.

4. Rename `ears-nfc-1.4.5.jar` to `ears.jar`.

5. Add `-javaagent:ears.jar` to Java Arguments.

6. Download [ModloaderNFC v4.6.1](https://github.com/New-Frontier-Craft/NFC-Addons/raw/main/NFC%2520v3.4.2/Addons/ModLoaderNFC%2520v4.6.1.zip)

7. Install as a jarmod. (MultiMC: Open Instance Edit Window, click `Version`, click `Add to Minecraft.jar`, find `ModLoaderNFC v4.6.1.zip` and click **Open.**

8. Launch the title.

9. Click on Singleplayer.

10. Create a New World, gamemode and seed do not matter.

11. Load into the world.

12. Observe Crash.

Results
------------------------------
Expected Result: Load into the world with both Ears and Modloader working

Actual Result: Title crashes

**Comment by exaskye** [comment]
Known. All of the retrofork ports are currently broken as they've all majorly refactored their skin handling (or the mod itself) and I haven't gotten around to fixing it.

**Comment by vskoldr21** [comment]
It seems to work without ModloaderNFC, interestingly enough. It's why I specified ModloaderNFC specifically.

![2022-10-21_01 57 10](https://user-images.githubusercontent.com/92074211/197142010-e786f609-0632-465f-97b1-65a7c73d9766.png)

However, given that ModloaderNFC will be merged into NFC 3.5.0, it's inevitable that it will be broken in general.

**Comment by exaskye** [comment]
Ears is now integrated with NFC, and this integration should not have this same bug. Please let me know if this persists even after the new NFC update.
