### ISSUE TITLE
Load player skins in Manipulator from URL fragment

### ISSUE THREAD

**Issue by exaskye** [exaskye/Ears#106]
When opening the Manipulator via the in-game options button, Ears puts the player's UUID into the URL fragment. The intent was to download the player's skin and pre-load it into the Manipulator.

**Comment by Flexico** [comment]
Wait, there's a way to edit skins in-game? :O

**Comment by exaskye** [comment]
No. Opening the Ears "options" in ModMenu or Forge just opens the Manipulator in your browser.
