### ISSUE TITLE
Infinite Loading Screen Loop on Pre-Release/Snapshot

### ISSUE THREAD

**Issue by MoonlightSystem** [exaskye/Ears#109]
Ears makes Minecraft stuck in an infinite loading loop with the latest pre-release
https://mclo.gs/z8E2f02

Mods List:
![image](https://user-images.githubusercontent.com/8211402/204845918-bf557868-009b-4687-ad63-776b74475724.png)

Fabric Loader 0.14.10
Minecraft version: 1.19.3 Pre-Release 2(also happens with prerelease 3)

**Comment by ghost** [comment]
Also happens on Full Release 1.19.3 (Quilt)

**Comment by ghost** [comment]
It seems like the net.minecraft.util.math package was nerfed a lot, removing the directly needed Matrix3f, Matrix4f and Vec3f and also eg. Quaternion, but adding MatrixUtil.class, which imports those/similar classes from org.joml. I will try to fix this ASAP.

**Comment by exaskye** [comment]
Yes, I'm aware of what has changed in 1.19.3. I've not yet gotten around to porting Ears.
