### ISSUE TITLE
Port to Release v1.7.5?

### ISSUE THREAD

**Issue by Flexico** [exaskye/Ears#114]
I'm curious how the "Villager Invasion" April Fools' version of the game would interact with Ears, but there doesn't even seem to be a Forge version for it! That probably makes the port impossible, or at least very time consuming, but I thought I'd ask, just in case.

**Comment by exaskye** [comment]
The "Villager Invasion" is just a resource pack and alternate skin server. There's nothing special about 1.7.5, and so I'm not going to break my "last minor only" policy for it.
