### ISSUE TITLE
Ears don't render at the correct height

### ISSUE THREAD

**Issue by DerRoboMeister** [exaskye/Ears#12]
So, the version I used was 1.8.9, and I noticed a problem with the ears portion, and a problem with both parts of the mod.
The first problem is that, in 1.8.9, the ears render too high, and don't properly merge with the head. That may just be a preference thing, but that's just what I saw.
The second problem is that neither portion moves correctly when the player crouches - they instead just float in the air as though the player were still standing up.

![earstest](https://user-images.githubusercontent.com/23659870/104851987-36bc2180-58c6-11eb-8cd4-d49e4a853a7d.png)
![2021-01-17_13 15 40](https://user-images.githubusercontent.com/23659870/104851991-3cb20280-58c6-11eb-9507-71e77076683f.png)
![2021-01-17_13 15 38](https://user-images.githubusercontent.com/23659870/104851995-3f145c80-58c6-11eb-81b8-e269a8fdbc5c.png)
![2021-01-17_13 17 30](https://user-images.githubusercontent.com/23659870/104852027-5d7a5800-58c6-11eb-957b-eaa089b3a43e.png)

**Comment by exaskye** [comment]
God damn it past Mojang.
