### ISSUE TITLE
Mod Crashes in Forge for 1.19.4

### ISSUE THREAD

**Issue by GlitchSans24011** [exaskye/Ears#121]
I'm using the latest Ears Mod version, yet the game crashes on startup with the latest version of Forge. I don't know why this is happening, as I don't know Javascript. Please fix.

**Comment by exaskye** [comment]
Going to need a crash log.

**Comment by GlitchSans24011** [comment]
NVM, I just needed to downgrade Forge to the version before the latest one
at the time. I was using the one that ended in .40. I downgraded to the
version that ends in .39, & now it works. The latest compatible version of
Forge wasn't clearly in the file name, so I had to figure out what was
wrong by myself. I guess the tech troubleshooting skills a certain family
member of mine taught me came in handy, lol! I wish you the very best
in your future endeavors.

Thanks for your willingness to help me out,
GlitchSans24011

**Comment by exaskye** [comment]
Works fine for me on Forge 45.0.40. Again, going to need a log.
