### ISSUE TITLE
[Feature] Compatability with 3d Skin Layers

### ISSUE THREAD

**Issue by BeeFox-sys** [exaskye/Ears#124]
It would be really nice to have compatibility with [3d skin layers](https://github.com/tr7zw/3d-Skin-Layers/), so that if someone has the mod, the 2d planes can render 3d. skin layers has an api though i haven't looked into it, but hopefully it can allow easier access, and at the same time resolve [issue 61](https://github.com/unascribed/Ears/issues/61)

(though i do understand the reluctance as it would mean that only people on fabric/quilt can access this feature)

**Comment by exaskye** [comment]
I can't just "add compatibility with 3D skin layers" due to how the Ears renderer is structured. It sounds like a shortcut but it's the opposite.
