### ISSUE TITLE
Doesn't appear to be working.

### ISSUE THREAD

**Issue by llloyd4** [exaskye/Ears#125]
Ok. So. I nabbed my skin, uploaded it to the Manipulator website, started to tweak on it, and didn't see any changes happening. Added ears, no ears appeared on screen. Added tail, no tail showed up on screen, tweaked with tail segments, nothing. Much like the Emperor's new clothing, it appeared to be illusionary. Still, saved the skin, uploaded it to Mojang, Loaded up the Launcher, launched the Forge instance of 1.19.2, loaded up my world, and switched view to 3rd person, and nothing was showing up. Mod is installed, 

![Screenshot 2023-04-06 06-17-42](https://user-images.githubusercontent.com/7238110/230390638-497ac798-e030-4b8b-8a3a-bc4ae9786a0d.png)

![Screenshot 2023-04-06 06-18-37](https://user-images.githubusercontent.com/7238110/230390695-246cf8c2-3d2f-4e12-89aa-8fa24526f3d9.png)

![Minecraft White Tiger Update Skin 4 6 2023](https://user-images.githubusercontent.com/7238110/230390954-821a0d68-7afb-4dd9-9a99-bf3d3eaf52f6.png)

**Comment by NyaomiDEV** [comment]
you're expected to design your own ears / tail, put them in the skin in the places the mod expects them to be, then use the web editor to configure positioning.

**Comment by llloyd4** [comment]
O.o I'm no artist. Umm, crud. I miss the Tails mod, it was for dummies like me >.<
