### ISSUE TITLE
1.7.10 Optifine Incompatibility

### ISSUE THREAD

**Issue by charagarlnad** [exaskye/Ears#13]
Ears v1.1.0 & Optifine HD_U_D6 ( happens with latest HD_U_E7 too, using HD_U_D6 due to higher performance )
I know this is a stretch to ask for Optifine compatability, but 1.7.10's performance is really miserable without it, even with foamfix17 + fastcraft + more. Do note that Lumy Skin Patch + SkinPort avoids this issue, likely due to the total replacement of the player renderer.

![2021-01-23_22 42 31](https://user-images.githubusercontent.com/27380203/105621368-55418180-5dcc-11eb-800f-3f38f11c3c8c.png)

**Comment by exaskye** [comment]
Ughhhhhhhhhh. OptiFine why are you like this

**Comment by exaskye** [comment]
v1.2.0_01 may fix this; please check.

**Comment by charagarlnad** [comment]
Works fine w/ Optifine + DAPI, thank you so much!
![image](https://user-images.githubusercontent.com/27380203/107855687-61c46300-6de9-11eb-994e-c5f48ac816cf.png)
