### ISSUE TITLE
Mod doesn't apply to Offline skins

### ISSUE THREAD

**Issue by Flexico** [exaskye/Ears#134]
When I play MC offline, I use a resource pack to change the player skin to my character, but the Ears addons don't appear. In older versions like beta 1.7.3 and release 1.2.5, the skin even appears stretched and distorted!
![2023-07-29_11 08 02](https://github.com/unascribed/Ears/assets/5751770/b691b502-33a4-4598-979f-da93af02071e)
![2023-07-29_11 07 53](https://github.com/unascribed/Ears/assets/5751770/c245129d-9b24-4781-9cc7-85e6ea71589e)

**Comment by exaskye** [comment]
The fallback skin from the resource manager does not go through the normal skin loading machinery, and so none of Ears' code runs.

**Comment by Flexico** [comment]
Could I ask for that as a feature? :3c

**Comment by k0nstruct** [comment]
https://modrinth.com/mod/selfskin works!
