### ISSUE TITLE
[Port Request] PaperMC 1.20.4

### ISSUE THREAD

**Issue by linryn** [exaskye/Ears#146]
Any possibility for a port to Paper/Bukkit/Spigot? Would love to add this to my server but I’m not running Fabric.

**Comment by exaskye** [comment]
Ears is client-only. It works in multiplayer because all the data is in the vanilla skin, no data is sent over the server and the server is entirely unaware of whether or not Ears exists.

As such, two Ears clients on a Bukkit server can already see eachothers' skin features.

**Comment by linryn** [comment]
Sorry, I must’ve been misunderstanding then, thanks
