### ISSUE TITLE
Game crashes upon entering a world [Quilt 1.20.2+ & Fabric 1.20.2+]

### ISSUE THREAD

**Issue by Antikyth** [exaskye/Ears#148]
When I try to enter a world, either an existing one or a new one, on 1.20.4, it crashes. I haven't tested other versions yet, but I can confirm that this happens on both the 1.20.4 Quilt version (both without or with Quilt Standard Libraries + FAPI Bundle, no other mods) and the 1.20.4 Fabric version (both without or with FAPI, no other mods).

This happens both with Experiments enabled and disabled, this crash report has them enabled, though.

Edit: the same crash also happens on 1.20.3 and 1.20.2, but not 1.20.1.

[1.20.4 Fabric (with FAPI) crash report](https://gist.github.com/Antikyth/7ce59acb13e147df3037361676a06d62)

**Comment by exaskye** [comment]
You are using the wrong Ears build — the one for 1.20.0/1.20.1, rather than the [1.20.2+ release](https://modrinth.com/mod/ears/version/1.4.6+fabric-1.20.2).

**Comment by exaskye** [comment]
Ears in general has very loose version specs in its fabric.mod.json as it's a mod that often does not need porting across versions. Going back and making new releases of old versions just to tighten their version specs to end at their final working version is a little silly, but it can lead to this sort of confusion.

**Comment by Antikyth** [comment]
> You are using the wrong Ears build — the one for 1.20.0/1.20.1, rather than the [1.20.2+ release](https://modrinth.com/mod/ears/version/1.4.6+fabric-1.20.2).

I see. This is the version provided on your website as 1.20.x with no 1.20.2 version listed, I think the website is outdated in that case. Thanks.
