### ISSUE TITLE
Compatibility with "OfflineSkins" mod

### ISSUE THREAD

**Issue by DedMaxim** [exaskye/Ears#153]
Features of "Ears" mod stop working if "OfflineSkins" is installed. Everything works, just without any "Ears" features. I've read few similar tickets. However, they were talking about using a skin from the resource pack. Here it's kinda similar, yet different situation. "OfflineSkins" allows skins to work on a server with online-mode=false. So, right now on such servers, there is really no way to see any of "Ears" features. So, would be nice if "Ears" supported "OfflineSkins" in some way.

Minecraft 1.20.1
Forge 47.2.20
Ears 1.4.6
OfflineSkins v1

**Comment by Flexico** [comment]
I second this! I often play offline and use a resource pack to turn the default skin into me, but Ears doesn't work with that either.

**Comment by k0nstruct** [comment]
You can use [Selfskin](https://modrinth.com/mod/selfskin)! it's compatible with Ears!

**Comment by DedMaxim** [comment]
You can use [Selfskin](https://modrinth.com/mod/selfskin)! it's compatible with Ears!

Oh, never heard of it before. Just tried, works perfectly and even launched on Forge through Sinytra Connector! Thanks!

**Comment by Mineralium** [comment]
@DedMaxim  Selfskin doesn't support 1.21, while OfflineSkins already works on 1.21.4, so I think this should still be looked into at some point.

**Comment by Gabryx64** [comment]
is there any plan to support offlineskins? i play on a 1.12.2 server with it so it would be cool if it worked
