### ISSUE TITLE
Tail remains at incorrect height while crouching

### ISSUE THREAD

**Issue by DerRoboMeister** [exaskye/Ears#17]
1.8.9
Ran the latest version of the mod, and while the ears are fixed, the tail isn't
![2021-02-12_14 20 00](https://user-images.githubusercontent.com/23659870/107812322-819e4d00-6d3d-11eb-94a3-2a6e33734a38.png)

**Comment by exaskye** [comment]
🤦‍♀️

**Comment by exaskye** [comment]
Fix released as v1.2.0_01
