### ISSUE TITLE
No documentation for ear orientations

### ISSUE THREAD

**Issue by TheSpiderDungeon** [exaskye/Ears#18]
The wiki still has documentation for the initial ear style (#3F23D8) but nothing for 1.2.0.

**Comment by exaskye** [comment]
Yes, this is mentioned in the changelog.

**Comment by exaskye** [comment]
The new format is a bit too complex for reasonably short documentation, so I've been working on a "skin manipulator" to do it: 

![image](https://user-images.githubusercontent.com/6185037/107841296-b24aaa80-6d6e-11eb-8132-89384616df80.png)

It's not quite done yet.

**Comment by TheSpiderDungeon** [comment]
Aye, fair enough then. Good luck with your tool!

**Comment by timelady-victorious** [comment]
YAYS. I can't wait for the tool, this is quite complex right now.
