### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by timelady-victorious** [exaskye/Ears#20]
I am 90% sure this is my fault, but i don't know what to do...
https://paste.ee/p/b1xCp (latest.log)
I copied the skin file from the tutorial, and uploaded it to minecraft.net. 
Nothing. No ears....
(modlist is inside latestlog)
![image](https://user-images.githubusercontent.com/73656286/110205031-25c37180-7e6e-11eb-92e5-71417a11d0fa.png)
Any help? (sorry for bothering you)

**Comment by exaskye** [comment]
Does it work without OptiFine?

**Comment by timelady-victorious** [comment]
Ah, I'll try soon. I am switching to sodium slowly.

**Comment by exaskye** [comment]
Closing as this has been awaiting a response since March. If you still have issues, reply and I'll reopen.

I generally can't be expected to support OptiFine as it's a closed source mod that makes innumerable invasive changes to the rendering engine.
