### ISSUE TITLE
What are Lossy pngs, And how do I fix the blue square?

### ISSUE THREAD

**Issue by BlueBirdAzurite** [exaskye/Ears#21]
Hello,
I installed your mod and followed the skin instructions for a skin of my fursona. however, for some odd reason the blue square doesn't want to show up for the mod. where should i set my skin to make it work? does it go in a special folder? thanks.

-- Iolite 
![rudy cute skin furry fancy tail](https://user-images.githubusercontent.com/31323726/110799530-406c6080-8249-11eb-9ced-146cff5006ee.png)

**Comment by exaskye** [comment]
Seems your question got answered in the Discord; square's in the wrong spot. Closing.
