### ISSUE TITLE
Ears Skin Manipulator Renders Wrong

### ISSUE THREAD

**Issue by Fairweather-Furry** [exaskye/Ears#22]
In the Ears Skin Manipulator, using the ear mode "around" displays the left and right side ear sections that are on the back side differently to ingame, with them seeming to be switched around. I've tested in-game to 1.12.2, 1.16.5 Fabric, and 1.16.5 Forge, all of them display the same in-game, but the preview on ESM is different. Left is in-game, right is ESM.
![error](https://user-images.githubusercontent.com/33701437/112743944-c8e94180-8f69-11eb-8161-b3b4db7a10d0.png)

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/112743992-f7a6ee00-8f50-11eb-90c1-1aec35cb8fef.png)

**Comment by exaskye** [comment]
This *is* confusing, but there's not a whole lot I could've done about it. Sorry.

**Comment by Fairweather-Furry** [comment]
No worry, I must've missed that notice somehow. Thanks for the quick response!
