### ISSUE TITLE
Ears and tail not showing

### ISSUE THREAD

**Issue by ArcticLightning** [exaskye/Ears#23]
most likely i did something wrong, but i dont know what is the problem.
my skin: 
![Rimuru_ears1](https://user-images.githubusercontent.com/76656422/113898853-e8d3fd00-97d4-11eb-96ff-fa8050f20e98.png)
i removed optifine as well but it didnt help

**Comment by exaskye** [comment]
Your skin is missing the magic activation pixels. Ears isn't on unless requested with these pixels as the areas Ears uses are sometimes filled with palettes, credit, solid color, etc.

You can upload your skin to the [Manipulator](https://unascribed.com/ears) to generate the necessary pixels and preview the options.
