### ISSUE TITLE
Port it to Beta 1.7.3 Cursed-Legacy (Fabric)

### ISSUE THREAD

**Issue by moechakucha** [exaskye/Ears#24]
Just as the title said.
https://minecraft-cursed-legacy.github.io/

**Comment by moechakucha** [comment]
Maybe using StAPI then?

**Comment by Cynosphere** [comment]
API's aren't the limitation, its how primitive model parts are back then when it comes to attaching new ones. I was working on the port before frustration burnout hit me, the only issues with it are rotations and some issues with drawing stack causing issues elsewhere when rendering.
