### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Celestius3** [exaskye/Ears#27]
Not sure what I have done wrong, but I copied the skin from the Skin Manipulator, brought it into my mc launcher, with optifine, on forge, and the mod itself loads just fine, just the tail texture doesn't sadly, any suggestions?

**Comment by exaskye** [comment]
Please post the log `.minecraft/logs/debug.log` to [Gist](https://gist.github.com).

**Comment by exaskye** [comment]
Closing due to no response and no actionable info in original report.
