### ISSUE TITLE
Black bar on skin

### ISSUE THREAD

**Issue by friyes** [exaskye/Ears#28]
Using the ears skin manipulator I made this skin: 
![canvas](https://user-images.githubusercontent.com/34990104/124365430-3f23d100-dc48-11eb-95ab-d28b5c9144d5.png)
But in-game a black bar appears on the back of the skin.
![image](https://user-images.githubusercontent.com/34990104/124365450-6aa6bb80-dc48-11eb-98f4-f6ab23ddfaf6.png)
How to fix?

**Comment by Cynosphere** [comment]
If you have First Person Model installed, it is incompatible with Ears

**Comment by friyes** [comment]
oh

**Comment by Cynosphere** [comment]
To be fair, it was attempted to be fixed some time ago, but it seems to have cropped up again as an issue. I don't know if its 1.17 specific or not that its an issue, as that was the only time I've attempted to use First Person Model with Ears.
