### ISSUE TITLE
Port to 1.18 Experimental Snapspot 1

### ISSUE THREAD

**Issue by moechakucha** [exaskye/Ears#29]
As the title says.
It's quite hard if you want to solve the "Minecraft problem" as this version was released alone.

**Comment by LucilleTea** [comment]
Ears for 1.17 is already compatible.
![2021-07-15_13 27 06](https://user-images.githubusercontent.com/64509677/125726756-f15bc20c-c969-4407-a64b-7bc83b93e849.png)
