### ISSUE TITLE
Claws render one pixel off on slim model (Manipulator claims fixed in v1.2.2)

### ISSUE THREAD

**Issue by AurySystem** [exaskye/Ears#30]
Not much to say here, Claws still render off by one pixel on the left arm in v1.2.2, and the skin manipulator says:

>"You've selected options that had bugs fixed in v1.2.2.
Before v1.2.2:
>
>- Sides, Floppy, and Behind modes had their back face texture locations swapped
>
>- ***Claws rendered one pixel off on the left arm for slim models***"

Maybe add next release not fixed yet text to it or like another version for it's fix? or put out a 1.2.3 prerelease?

**Comment by exaskye** [comment]
....This is the thing I forgot to fix before the v1.2.2 release. Whoops.
