### ISSUE TITLE
"Behind" Ear Mode & Tail Underside

### ISSUE THREAD

**Issue by DegeneracyIsNotOK** [exaskye/Ears#32]
The "behind" ear mode is not affected by ear anchor changes, _at least not in the skin manipulator_. Would it be possible to make it work as is pictured below.
![Screenshot_2](https://user-images.githubusercontent.com/73244061/129419824-e5830aa0-8539-4b97-821b-df1254ee7de2.png)

Seeing as there are no unused 12x8 regions left in the skin file. Would it be possible to stitch together two non-adjacent boxes in-game and use them for the tail underside?
![Screenshot_5](https://user-images.githubusercontent.com/73244061/129420145-14571179-f696-4d18-ab45-f263a3300ec5.png)
_(The recoloured blue tail has been cut into 8x8 and 8x4 pieces and put into the far right and far left unused squares of same size.)_

While the tail underside region is not a necessity as is the case with the ear backside, it would enhance customization.

**Comment by exaskye** [comment]
The top left 8x8 is a "safe zone" I refuse to use as it's the most common place for other mods and older systems to put encoded data.

Changing behind ear anchor to work like that makes a lot of sense.

**Comment by exaskye** [comment]
Added as a new "Out" ears mode, for compatibility. (The default ear anchor is "Center", so this would have unexpected results for anyone currently using "Behind" mode.)

Tail backside is probably not going to be added, as it's difficult to see it in-game and uses a lot of pixels that could have other purposes.
