### ISSUE TITLE
Ears 1.17.1 Forge crashes during loading process.

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [exaskye/Ears#36]
hey, sorry. I forgot to mention this in my Curseforge comment yesterday, but the game crashes during loading with the latest version of Ears for Forge 1.17.1 when attempting to launching with a version of Forge 1.17.1 that has Mixin built-in.

Crash Log:
[crash-2021-10-22_16.13.29-client.txt](https://github.com/unascribed/Ears/files/7402235/crash-2021-10-22_16.13.29-client.txt)

(Second Time Attempting To Submit This Crash Log)

**Comment by exaskye** [comment]
The 1.17 Forge build appears to be missing the refmap.

**Comment by exaskye** [comment]
I don't think this build ever worked.

Would have been nice if someone told me so earlier, especially considering what a big deal I made of the fact *I cannot test it myself*...

**Comment by exaskye** [comment]
Please try this build: https://unascribed.com/f/b4810c35/ears-forge-1.17-1.3.0_01-pre1.jar

**Comment by AlexTheSuprWolf** [comment]
> Please try this build: https://unascribed.com/f/b4810c35/ears-forge-1.17-1.3.0_01-pre1.jar

This version seams to have fixed the problem. Mod functions perfectly by itself.

**Comment by exaskye** [comment]
Published as v1.3.0_01.
