### ISSUE TITLE
Magic pixels to hide sections of second layer

### ISSUE THREAD

**Issue by RuinTD** [exaskye/Ears#39]
There should be magic pixels that allow the user to hide certain sections of the base skin's second layer (hat, jacket, etc). This would be useful for if the user already has ears or tails on their base skin that should be hidden if using the Ears mod.

unascribed's suggested implementation would involve the user specifying coordinates of the skin to hide.
https://discord.com/channels/813954820460642336/813954820460642339/904087220506493009

**Comment by exaskye** [comment]
There are now skins in the wild using this feature, so I'm going to close this. Manipulator support is another issue.
