### ISSUE TITLE
 [FORGE 1.16] Ears v1.4.1 server crash

### ISSUE THREAD

**Issue by SunnyMenkov** [exaskye/Ears#41]
server can't start on 1.4.1
on 1.4.0 everything is ok
crash log
[crash-2021-11-19_16.41.13-fml.txt](https://github.com/unascribed/Ears/files/7571823/crash-2021-11-19_16.41.13-fml.txt)
g

**Comment by Cynosphere** [comment]
Ears is purely client sided and not required on the server.

**Comment by exaskye** [comment]
I should probably ensure the mod doesn't load at all on servers, but yes, Ears is strictly client-only.

**Comment by spiritedsnowcat** [comment]
Hey there! Is it possible to add that check in so it doesn't load on servers? If the mod isn't included in the forge server, then the server-client compatibility check in the client's server menu says "incompatible". There're mods to bypass that, but I've been saved by that compatibility check before. If I knew how to add it, I'd make a pull request myself (definitely will keep an eye on what a change like that looks like). Thanks!
