### ISSUE TITLE
1.7.10 - Slim Arms stop being slim upon death

### ISSUE THREAD

**Issue by Not-February** [exaskye/Ears#45]
Before death:
![image](https://user-images.githubusercontent.com/13922447/142815766-1ee71d5d-026a-4803-a066-445e6425d8d9.png)

![image](https://user-images.githubusercontent.com/13922447/142815789-bc0868c1-ad1f-4396-979f-74fd6262fc98.png)
After respawning:
![image](https://user-images.githubusercontent.com/13922447/142815804-ebef0d3b-6858-45bf-831e-412b8b45943e.png)

This was observed with only ``Forge 10.13.4.1614`` and ``Ears1.4.1`` installed.

Of interest: Installing [bspkrsCore](https://www.curseforge.com/minecraft/mc-mods/bspkrscore), which adds a renderer to the main menu of the player and a random mob, seems to also display this behavior somewhat. Ater loading up the game for the first time, the player renders correctly on the menu:

![image](https://user-images.githubusercontent.com/13922447/142816121-ca0fa6b8-5183-4994-bffe-791cc1e7ced1.png)
But after navigating away from the title screen and back, it's broken now:
![image](https://user-images.githubusercontent.com/13922447/142816165-0a3d119b-ab24-4a90-9eca-50629254a423.png)

This leads me to believe that the issue only occurs when the player model is completely re-rendered, like when the player respawns or in situations like the model being rendered on the main menu.

**Comment by exaskye** [comment]
1.7 is a really awkward version as it's before the 1.8 player model changes but after the API rework; will look at this

**Comment by exaskye** [comment]
I have to wonder if it'd be better to just treat 1.7 as a vlegacy version and ignore its janky partial implementation of the new skin system...
