### ISSUE TITLE
Crash on load in 1.8.9

### ISSUE THREAD

**Issue by Gronglegrowth** [exaskye/Ears#46]
Loading Ears alone does not result in any crashes, but with the other mods I have for 1.8.9, something results in a game crash. I will attempt to find which of my mods is causing it, as the crash report does not seem to mention anything but Ears,
[crash-2021-11-22_23.19.05-client.txt](https://github.com/unascribed/Ears/files/7585835/crash-2021-11-22_23.19.05-client.txt
[fml-client-3.log](https://github.com/unascribed/Ears/files/7585851/fml-client-3.log)
)

**Comment by exaskye** [comment]
Some other mod you have installed has ASM patched the vanilla skin system in a way that Ears no longer recognizes it. My first suggestion for something to remove would be MorePlayerModels.

**Comment by exaskye** [comment]
Wait, you have OptiFine, and MorePlayerModels doesn't show up in the coremod list at the top. Much more likely cause.

I cannot do anything for OptiFine compatibility as it is an invasive closed-source mod.

**Comment by Gronglegrowth** [comment]
It was indeed Optifine
