### ISSUE TITLE
1.7.10 - backported skin layers don't turn invisible with the rest of the player

### ISSUE THREAD

**Issue by Not-February** [exaskye/Ears#49]
![image](https://user-images.githubusercontent.com/13922447/144004238-5d4d45eb-f11b-4c71-b442-2d6b2364ba52.png)

I've noticed this on myself as well (my second layer is the cloak)

![image](https://user-images.githubusercontent.com/13922447/144011431-56662e95-f1ab-4f3f-9048-ecd794b060c2.png)

![image](https://user-images.githubusercontent.com/13922447/144011469-b310e0b6-769c-404c-92a2-47ac9020a8e3.png)

Currently using version ``Ears 1.4.1`` and ``Forge 10.13.4.1614``, and I did see that there's a newer version, but didn't see anything in the changelog indicating this particular issue being addressed. so I don't think it would make a difference?

**Comment by exaskye** [comment]
Ah, this would be because of my move from adding the secondary layers to the vanilla boxes to doing the rendering in Common. I'll have to expose invisibility state to Common.
