### ISSUE TITLE
[1.18.1] Client-Server compatibility check fails

### ISSUE THREAD

**Issue by spiritedsnowcat** [exaskye/Ears#54]
Hi there, 

It looks like if Ears isn't included on the forge server side (which currently crashes the server), then the server compatibility check in the client fails. BetterF3 is a similar client-side mod that doesn't have this problem. BetterF3 crashes on server startup similarly to Ears, but not including it on the server doesn't fail the compatibility check. Could it be something with how they configured their mod?

Thanks,
Spirited

**Comment by Cynosphere** [comment]
Forge's compatibility check has always been horrible and doesn't mean anything other than an icon in the server list. If you can still connect then it doesn't matter honestly.

**Comment by spiritedsnowcat** [comment]
It'd still be nice to have that check passing. That check has saved my butt a few times now, so I'd like for it to be passing for my little home server's modpack. Maybe I'm just bad at maintaining modpacks with my server, but it'd give me a lot of peace of mind. I'd make the change myself, but I'm not sure what I need to change for this. Thanks for your time.

**Comment by spiritedsnowcat** [comment]
Oh, thanks so much for fixing this!
