### ISSUE TITLE
crashes on server join 1.8.9

### ISSUE THREAD

**Issue by Blogom** [exaskye/Ears#55]
So i set up all the things with the skin and what have you, tested it in singleplayer, but when i go to join hypixel i crash. 
![Screenshot_17](https://user-images.githubusercontent.com/96531240/147097762-81f56ab3-6f20-4217-8589-657532f34a90.png)
and also a list of the mods i have installed
![image](https://user-images.githubusercontent.com/96531240/147097873-623ff07c-59b4-43f5-96e3-79033cd6ec30.png)

**Comment by exaskye** [comment]
Already fixed, but hasn't been released yet. 1.4.3 will contain the fix.

**Comment by Blogom** [comment]
> Already fixed, but hasn't been released yet. 1.4.3 will contain the fix.

awesome, thank you. for now 1.3.0 seems to be stable on servers :)

**Comment by exaskye** [comment]
1.4.3 was released, containing this fix.
