### ISSUE TITLE
Port for the b1.7.3 "Better than Adventure" mod

### ISSUE THREAD

**Issue by VoyVivika** [exaskye/Ears#58]
I'd like to request a port of Ears for the "Better than Adventure" mod if it isn't too much trouble. BTA isn't compatible with mods for b1.7.3 and does not include a skin-fix.

**Comment by exaskye** [comment]
You'd assume this would be easy to do, but unfortunately this constitutes an entirely new platform port. The NFC port relies on NFC's own skin port, and the Fabric Cursed Legacy port relies on Mixin.

It's been on my todo, however.

**Comment by exaskye** [comment]
Some splicing together of the NFC, NSSS, and 1.2 ports later...

![image](https://user-images.githubusercontent.com/6185037/147814413-291ed60e-bdbe-4567-b97f-96ab656e276a.png)
