### ISSUE TITLE
Port to the April Fool's Infinity Snapshot?

### ISSUE THREAD

**Issue by Flexico** [exaskye/Ears#60]
Am I the only one who still plays this sometimes? Hopefully not! X3 I know there's a Fabric version available for it~

**Comment by Cynosphere** [comment]
Since 20w14∞ was during the 1.16 development cycle, you could try the 1.15 or 1.16 verison and see if it works.

**Comment by Flexico** [comment]
Ooooohh, good point! I'm-a go do that~

**Comment by Flexico** [comment]
Hooray, it works! =D Unlike Fabric API for that version, but I'll complain about that elsewhere... XD
