### ISSUE TITLE
Instant Crash in 1.17.1 Fabric

### ISSUE THREAD

**Issue by DaveHyral** [exaskye/Ears#68]
"Cannot read field "enableInitLoadingScreen" because "net.morimori.mus.MemoryUsageScreen.CONFIG" is null. "
Crash Log has been supplied, plz advise.
[crash-2022-01-24_16.43.42-client.txt](https://github.com/unascribed/Ears/files/7929346/crash-2022-01-24_16.43.42-client.txt)
l

**Comment by exaskye** [comment]
Nothing to do with Ears. Seems to be "memoryusagescreen".
