### ISSUE TITLE
Unexpected Error crash when trying to set non-slim model on player with slim model active

### ISSUE THREAD

**Issue by Skeithh** [exaskye/Ears#72]
Hello! My friend ran into this issue just a bit ago. They were trying to set a skin that was not slim, and thus did not tick the slim box either. Their player model, by default (as selected in the base minecraft skin selector), is slim though. The skin works fine when the slim box is ticked.

[crash-2022-02-20_13.08.20-client.txt](https://github.com/unascribed/Ears/files/8103945/crash-2022-02-20_13.08.20-client.txt)

Mod version: 
ears-fabric-1.17-1.4.5_01

**Comment by Infinidoge** [comment]
Is this reproducible with only Ears installed? (I can see that there are a lot of other mods installed.)

**Comment by Skeithh** [comment]
will attempt a clean test with the mod once I can and then I'll get back to you!
