### ISSUE TITLE
Emissive Colours Breaks Affects Wing Rendering

### ISSUE THREAD

**Issue by MayliSong** [exaskye/Ears#74]
(To start, I know the emissive colours are considered beta and so bugs are to be expected)
I'm not sure if it's specific to the wing texture I was using, but attempting to put emissive colours on my texture also causes a significant chunk of the wing to become emissive even if no colour on the wings is close to an emissive. 
The only emissive colours on this skin are 3 shades of blue, and I've also tested filling in the rest of the 4x4 with black/a colour not on the skin and by leaving the space blank, in case it had to do with the transparency used to encode the wings. Using the Forge 1.18 v1.4.5 release
![phoenix(ears)2](https://user-images.githubusercontent.com/63749441/162869006-3af01cd7-b6d3-4ac7-99ef-f70196d4c6b3.png)
![Screenshot_2](https://user-images.githubusercontent.com/63749441/162869016-7b660667-659b-4832-8c40-854f8b837b80.png)
(Even if it is not what I want, the part of the wings glowing does look pretty spectacular though.)

**Comment by exaskye** [comment]
Already fixed in trunk, but I haven't released it yet for some reason.

Emissive colors and big wings is a fairly rare combo, so.

**Comment by exaskye** [comment]
Here: https://unascribed.com/f/c94094ac/ears-forge-1.18-1.4.6-pre1.jar

**Comment by MayliSong** [comment]
Oh wow, I appreciate the fix! I wasn't expecting much, just figured I'd bring it up in case it wasn't a known issue. But yeah, works like a charm, thank you!
