### ISSUE TITLE
1.18.2 Fabric - Skin Not Loading?

### ISSUE THREAD

**Issue by saevyper** [exaskye/Ears#76]
Hello! I honestly may just be doing something wrong.. I saw that 1.18.2 is supported on another part of the forum.

Basically, I've installed the mod (downloaded + saved in the .minecraft/mods file), and the game launches and plays. But the skin I've uploaded does not have the ears or tail included. (I'm also unsure where to add the wings?) I uploaded the skin via the Minecraft Launcher. This is also on the Fabric version, and not the Forge, I'm unsure if that matters. (OptiFine is NOT downloaded)

**Comment by exaskye** [comment]
What is your username?

**Comment by saevyper** [comment]
saevyper on Minecraft as well

**Comment by exaskye** [comment]
Your skin does not have any magic pixels. Load it into [the Manipulator](https://ears.unascribed.com/manipulator) and configure your desired features, **then save and upload the resulting skin**.

**Comment by saevyper** [comment]
OMG thank you so much, I knew I was doing something wrong.
AWESOME MOD BY THE WAY <33
