### ISSUE TITLE
Request for side-facing ears

### ISSUE THREAD

**Issue by TheSpiderDungeon** [exaskye/Ears#8]
This mod is really slick and has a lot of promise! I've taken a look at how you've implemented it, and it's really clever. However, it only supports front-facing ears.

Based on how you've done the ears currently, I would offer a suggestion to use the same system but with some tweaks. Instead of #3F23D8 you use #3F23D9 or #3F23D7 to signify the difference in ear position to the mod without adding any toggle GUI or config file, so as to keep the simplicity of the mod. This would tell the mod to render two ear segments instead of one, rotate it, place it at the side of the head instead of the top, and mirror it on the other side.

Obviously the limitation would be that the ears will always be symmetrical, but it would keep the simple nature of the mod, wouldn't require any differences to the existing skin system, _and_ still permit users to make the fronts and backs of the ears.

**Comment by TheSpiderDungeon** [comment]
Also I have no idea how to add a label. My apologies.

**Comment by TheSpiderDungeon** [comment]
![image](https://user-images.githubusercontent.com/14132982/96341416-78db8a00-106f-11eb-97f0-9826986c6189.png)

Something I slapped together in Paint.NET

**Comment by exaskye** [comment]
I do already intend to have multiple versions of the skin format with slightly different colors, so this fits in well with that. I think I'd rather take a feature selection approach; it's why I claimed a 4×4 area. So you could for example set the second pixel to magic blue for current behavior, magic green for this behavior, or black to disable usage of the ears regions.

Blocked by #5

**Comment by exaskye** [comment]
> Also I have no idea how to add a label. My apologies.

I don't believe non-collaborators have permission; I just reworked the labels in any case.

**Comment by exaskye** [comment]
One thing is, this overlaps with the vanilla headwear. Because of this you could actually divvy up the ears regions into 8×8s and get asymmetrical ears.

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/98891104-56604500-2452-11eb-9e8f-c35987057abd.png)

Will be released with 1.1.1.
