### ISSUE TITLE
Usage of the mod

### ISSUE THREAD

**Issue by SuperSurferNow** [exaskye/Ears#80]
Look idk how to use the mod can you help me and make the mod less compliation my discord is SuperSerferNow#0236. If this is agisn't the tos or smthing i didn't read it it's so long anyways good day bye.

**Comment by exaskye** [comment]
I can't help you if you refuse to read.

Using Ears is not against the Minecraft ToS.

**Comment by exaskye** [comment]
If you have specific questions, you are welcome to [join my Discord](https://discord.gg/8WBauq2eYK) and ask them. I don't do support in DMs.
