### ISSUE TITLE
Crashes on 22w18a when player comes into view

### ISSUE THREAD

**Issue by Flexico** [exaskye/Ears#81]
Either hitting F5 or opening the survival inventory immediately crash the game with the following error:
The game crashed whilst rendering entity in world
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_630$class_628 net.minecraft.class_630.method_22700(java.util.Random)'
Exit Code: -1
https://pastebin.com/92swAzta

**Comment by LemmaEOF** [comment]
Looks like Mojang's changed the signature from `net.minecraft.client.model.ModelPart$Cuboid getRandomCuboid(java.util.Random)` to `net.minecraft.client.model.ModelPart$Cuboid getRandomCuboid(net.minecraft.util.math.AbstractRandom)`

**Comment by Flexico** [comment]
So they switched from Java's rng to their own function? Hah, I've done stuff like that before~

**Comment by LemmaEOF** [comment]
They've been switching to their own Random for a bit, mainly because Java's stock random is...[not the best lmao](https://www.youtube.com/watch?v=5Icj5TNmBUI)

**Comment by LemmaEOF** [comment]
Looking at the code, it looks like [`NotRandom`](https://github.com/unascribed/Ears/blob/trunk/common/src/main/java/com/unascribed/ears/common/util/NotRandom.java) will have to subclass `AbstractRandom` on new versions instead of just `Random`.

**Comment by Flexico** [comment]
Ooooohh, the find-diamonds-by-clay thing! I remember seeing people talk about that before.

**Comment by exaskye** [comment]
nooo<sup>ooooooo<sup>ooooooo</sup></sup>

**Comment by exaskye** [comment]
I'll note the "diamonds and clay correlate" isn't caused by java.util.Random's algorithmic weakness, it's caused by Mojang seeding different generators with the same seed.

**Comment by Flexico** [comment]
I can't help but sing this out loud, with "noooo" rising in pitch for each rising superscript! XD

**Comment by exaskye** [comment]
I released a 1.19 port the other day.

**Comment by Flexico** [comment]
Wooooo thanks! ^^
