### ISSUE TITLE
Skin Renders Wrongly in 1.4.7

### ISSUE THREAD

**Issue by Flexico** [exaskye/Ears#82]
When I use my full 64x64 skin in MC v1.4.7, it renders all wonky, but if I crop it to the old 64x32 size, it crops out the Ears mod data!
The [Lumy Skin Patch](https://www.curseforge.com/minecraft/mc-mods/lumy-skin-patch) that allows older versions to access the new skin server isn't working on version 1.4.7, so I had to use a texture pack to add my skin; I don't know if that's related or not.

**Comment by Flexico** [comment]
![2022-05-09_13 22 25](https://user-images.githubusercontent.com/5751770/167469807-c4f5a30d-fdb4-41d5-864f-6696bb11fc36.png)

**Comment by exaskye** [comment]
Ears itself contains a skin patch. Do not install Lumy Skin Patch.

**Comment by Flexico** [comment]
Ok, tried it without and I'm just Steve!

**Comment by exaskye** [comment]
Please post your mod list.

**Comment by Flexico** [comment]
Oooooohhh it has to be in the coremods folder! Now it works!!
