### ISSUE TITLE
Mod ears uses the version 1.4.5_01 which isn't compatible with Loader's extended semantic version format

### ISSUE THREAD

**Issue by Kino0208** [exaskye/Ears#88]
Loading Minecraft 1.18.2 with Fabric Loader 0.14.8
Mod ears uses the version 1.4.5_01 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5_01'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

**Comment by exaskye** [comment]
Not a bug.
