### ISSUE TITLE
[Fabric 1.18.2] Crashes when changing skin with Skin Swapper

### ISSUE THREAD

**Issue by feytox** [exaskye/Ears#89]
Minecraft crashes after 2-3 skin changes with the Skin Swapper mod when I use the Ears mod. The crash report says that the cause is the Ears mod.

Crash report - https://bytebin.lucko.me/BK0rNxDa1G

**Comment by exaskye** [comment]
The paste link has expired. Please use [Gist](https://gist.github.com) or similar.
