### ISSUE TITLE
Add toggle for ears that point down

### ISSUE THREAD

**Issue by Beethoven-n** [exaskye/Ears#9]
If you want to play as a dog character, certain breeds are currently kinda locked out, thanks to the fact that the ears region is drawn as a single rectangle pointing up from the top of the character's head.
If you wanted to play as a beagle, or a spaniel, or a shih tzu, you're kinda out of luck. I'd love for the ears region to be toggleable to split in half, and rendered on the sides of the player's head.
You could do this without GUI code in a similar manner to Mine Little Pony, which toggles various species information with differently colored pixels in other unused regions of the skin. You could also possibly toggle it by having the color at `0, 32` be something different, like red or orange.

**Comment by exaskye** [comment]
Additional regions are already being worked on for 1.1.1, including this.

**Comment by Vesperce** [comment]
Speaking of Mine Little Pony, the option for a forward-facing horn would be nice.

**Comment by exaskye** [comment]
Adding a 45° horn to my list. I was originally going to ask if it should be pointing straight up or straight forward, but 45° is probably the right choice. I think that's also the most MLP-y option, but I'm far from a pony expert.

**Comment by Beethoven-n** [comment]
that'd be correct! though it might look too dark on the bottom from exactly 45 degrees, maybe somewhat higher?

**Comment by exaskye** [comment]
I work on Ears as a minor side hobby. Some patience would be appreciated.

**Comment by Beethoven-n** [comment]
OH WOOPS i thought that closing it meant i was done talking about it, sorry!!

**Comment by Beethoven-n** [comment]
i also saw another issue that was similar to mine that got closed, so i thought that was okay

**Comment by exaskye** [comment]
The other issue was closed because I had finished implementation. Generally, issues are closed when the developer is done with them, to track what they need to do.

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/102847496-63d1fd00-440a-11eb-8695-aeb3db14e65c.png)
![image](https://user-images.githubusercontent.com/6185037/102847512-6b91a180-440a-11eb-9ed4-004f408ba79a.png)

Does this look right? The ability to change the anchor also exists; it doesn't have to be centered, it can be flush with the front or back of the head too.

**Comment by Beethoven-n** [comment]
keep this functionality in, it works for elephant skins! but for what i'm thinking of, i think the side areas would have to be mostly parallel to the head, not perpendicular
maybe add some tilt to it after rotating it that way, too

**Comment by exaskye** [comment]
Is that not covered by the vanilla headwear region or #8?

**Comment by exaskye** [comment]
Or do you *literally* want it to point *down*? That will clip into the player's arms and torso...

**Comment by exaskye** [comment]
(This at least explains why I was having such a hard time understanding the issue title.)

**Comment by Beethoven-n** [comment]
it's kind of covered by the headwear, but it doesn't look long enough, maybe something like ears that go behind the back? or maybe ears that come out from the top of the head and tilt towards the shoulders?? something like this
edit: added chest for some sort of actual context
![Untitled](https://user-images.githubusercontent.com/44652883/103304661-d4f74e80-49ce-11eb-88ab-02646596315e.png)

**Comment by Beethoven-n** [comment]
ears that go behind the back of the skin could work well for rabbit characters that have long ears like that too

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/107682891-c8b11300-6c55-11eb-9c59-ae9eabfd283b.png)
